export const SERVER_SENDER_ID = -1;
export const GAMEPLAY_UPDATE_INTERVAL = 1000 / 60;
export const GAMEPLAY_UPDATE_INTERVAL_SECS = 1 / 60;
export const NETWORK_UPDATE_INTERVAL = 100;
export const LAG_COMPENSATION_THRESHOLD = NETWORK_UPDATE_INTERVAL;
export const MAX_TICKS_WITHOUT_SERVER = 60;
